BryanDavidAlves/TrampoTec

pag-empresa/candidatos.php
pag-empresa/componentes/componentE.css
pag-empresa/componentes/rightbar-candidato.php
pag-empresa/componentes/rightbar-home.php
pag-empresa/componentes/rightbar-vagas.php
pag-empresa/configuracoes.php
pag-empresa/css/Candidatos.css
pag-empresa/css/PERFIL.css
pag-empresa/css/home.css
pag-empresa/css/vaga.css
pag-empresa/js/java-empresa.js
pag-empresa/vagas.php
pag-professor/css/notificaca.css

fiinalizando javascript e arrumando

terminando o js e estilizando ultimos cards

---

pag-empresa/beck-end/cadastro/funcoes.php
pag-empresa/beck-end/cadastro/salvarCadastro.php
pag-empresa/componentes/sidebar.php
pag-empresa/pags-logins/criar-login.php
pag-empresa/pags-logins/login.php

Verificação cnpj, e mascara cnpj prontos

Verificação cnpj, e mascara cnpj prontos

---

pag-empresa/css/login-cadastro.css
pag-empresa/css/login.css
pag-empresa/pags-logins/criar-login.php
pag-empresa/pags-logins/login.php

adicionando inputs

---

pag-adm/components/components.css
pag-etec/componentes/componente.css
pag-etec/componentes/sidebar.php
pag-etec/home.php

mechendo na sidebar etec

---

pag-etec/componentes/componente.css
pag-etec/componentes/filtro.php
pag-etec/componentes/sidebar.php
pag-etec/css/home.css

estilizando componentes

---

pag-etec/home.php

Arrumando link css da home

---

dao/bdtrampotec.sql
pag-aluno/beck-end/cadastro/funcoes.php
pag-aluno/beck-end/cadastro/salvarCadastro.php
pag-aluno/cadastro.php
pag-empresa/beck-end/cadastro/funcoes.php
pag-empresa/beck-end/cadastro/salvarCadastro.php
pag-empresa/pags-logins/criar-login.php

Cadastro realizado, com validações e atualização do banco

Cadastro aluno feito, com validações

---

one-page/css/descricao-alphatec.css
one-page/css/hom.css
one-page/css/servico.css
one-page/css/sobre.css
one-page/index.html
one-page/js/one-page.js

add pasta js em one-poge/estilizando animacao

add pasta js em one-poge/estilizando animacao

---

one-page/css/contato.css
one-page/index.html
pag-etec/componentes/sidebar.php
pag-etec/configuracoes.php
pag-etec/css/componente.css
pag-etec/css/configuracoes.css
pag-etec/css/perfil.css
pag-etec/home.php
pag-etec/perfil.php

apagando pagina curso/estilizando pag etec

apagando pagina curso/estilizando pag etec

---

assets/css/style.css
dao/bdtrampotec.sql
pag-aluno/beck-end/cadastro/salvarCadastro.php
pag-aluno/cadastro-old.php
pag-aluno/cadastro.php
pag-empresa/beck-end/cadastro/salvarCadastro.php

Cadastro do aluno feito, e select option de todas etecs

Aplicando select das ete, e cadastro

---

pag-adm/adm.php
pag-adm/back-end/cadastro/salvarCadastro.php
pag-adm/back-end/crudAdm/adm-delete.php
pag-empresa/beck-end/cadastro/salvarCadastro.php

Adicionando delete no adm

---

pag-adm/adm.php
pag-adm/aluno.php
pag-adm/back-end/login/logout.php
pag-adm/back-end/login/valida_login.php
pag-adm/back-end/login/validador_acesso.php
pag-adm/cadastro-adm.php
pag-adm/cadastro.php
pag-adm/components/sidebar-adm.php
pag-adm/configuracao.php
pag-adm/css/login.css
pag-adm/empresa.php
pag-adm/etec.php
pag-adm/index.php
pag-adm/login.php
pag-adm/notificacao.php
pag-adm/perfil.php
pag-adm/professor.php
pag-adm/relembrar-senha.php

Login adm feito

---

pag-empresa/cadastrar-vaga.php
pag-empresa/candidatos.php
pag-empresa/css/cadastrar-vaga.css
pag-empresa/css/login-cadastro.css
pag-empresa/css/vagas.css
pag-empresa/js/java-empresa.js
pag-empresa/vagas.php

estilizando cadastro vagas

---

pag-empresa/componentes/componentE.css
pag-empresa/configuracoes.php
pag-empresa/css/Candidatos.css
pag-empresa/css/PERFIL.css
pag-empresa/css/cadastrar-vaga.css
pag-empresa/css/conosco.css
pag-empresa/css/editar-vaga.css
pag-empresa/css/vagas.css
pag-empresa/editar-vaga.php
pag-empresa/perfil.php
pag-empresa/vagas.php

estilizando tela de alterar vaga

estilizando tela de alterar vaga

---

pag-empresa/cadastrar-vaga.php
pag-empresa/css/PERFIL.css
pag-empresa/js/java-empresa.js
pag-empresa/perfil.php

tela de editar perfil da empresa

tela de editar perfil da empresa

---

pag-adm/cadastro-curso.php
pag-adm/cadastro-etec.php
pag-adm/css/cadastro-curso.css

mexendo no cadastro do curso e etec / johny

mexendo no cadastro do curso e etec / johny

---

pag-adm/aluno.php
pag-adm/back-end/buscas/buscaAluno.php
pag-adm/back-end/buscas/buscaCurso.php
pag-adm/back-end/buscas/buscaEmpresa.php
pag-adm/back-end/buscas/buscaEtec.php
pag-adm/back-end/buscas/buscaProfessor.php
pag-adm/curso.php
pag-adm/empresa.php
pag-adm/etec.php
pag-adm/professor.php

sistema de busca aproximada funncionando

sistema de busca aproximada funncionando

---

pag-professor/alunos.php
pag-professor/components/sidebar.php
pag-professor/css/alunos.css
pag-professor/css/indicacar.css
pag-professor/css/perfil_aluno.css
pag-professor/index.php
pag-professor/perfil.php
pag-professor/perfil_aluno.php
pag-professor/vagas.php

Add nova pag de perfil aluno na pag-prof

Add nova pag de perfil aluno na pag-prof

---

pag-adm/css/index.css
pag-adm/index.php
pag-adm/relatorio.php

Resolvendo conflitos

---

pag-aluno/js/modal-vagas.js
pag-aluno/painel-de-vagas.php
pag-empresa/vagas.php

Só preciso arrumar os modal da tela da empresa e na tela do aluno

vagas aparecendo na area de vagas na tela dos alunos 

---

pag-adm/adm.php
pag-adm/back-end/buscas/buscaAdm.php
pag-empresa/componentes/componentE.css

sistema de busca na area de adm

sistema de busca na area de adm

---

pag-adm/css/index.css
pag-adm/index.php
pag-empresa/css/dash.css
pag-empresa/dash.php

graficos da dashboard adm

---

pag-adm/cadastro-etec.php
pag-adm/css/cadastro-etec.css

estilizando geradoes de campos

estilizando geradoes de campos

---

assets/css/style.css

estilizando tela de login empresa

estilizando tela de login empresa

---

pag-adm/js/professor.js
pag-adm/login.php
pag-adm/relembrar-senha.php
pag-aluno/css/envia-link.css
pag-aluno/css/login.css
pag-aluno/login.php
pag-professor/back-end/cadastro/salvarCadastro.php
pag-professor/cadastro.php
pag-professor/css/cadastro.css

Arrumando telas de login

---

pag-aluno/EnviarRecomendacao.php
pag-aluno/recomendacoes.php
pag-professor/index.php
pag-professor/indicacao.php
pag-professor/perfil_aluno.php

Juntando as partes

---

pag-adm/index.php
pag-aluno/back-end/salvarCandidato/salvar-candidato.php
pag-aluno/painel-de-vagas.php
pag-empresa/beck-end/alterar/update.php
pag-empresa/beck-end/cadastroVaga/salvarCadastroVaga.php
pag-empresa/componentes/sidebar.php
pag-empresa/css/candidato-vaga.css
pag-empresa/perfil.php
pag-empresa/vagas-candidato.php
pag-empresa/vagas.php

Criando nova tela de pendentes

Criando nova tela de pendentes

---

pag-aluno/painel-de-vagas.php

filtragem quase finalizada

---

pag-aluno/css/painel-de-vagas.css
pag-aluno/painel-de-vagas.php

filtragem com selects do aluno feita

filtragem com selects do aluno feita

---

pag-adm/cadastrar-curso-etec.php

Reverts BryanDavidAlves/TrampoTec#200

Revert "substituindo o datalist por select"

---

pag-aluno/painel-de-vagas.php
pag-aluno/processos-seletivos.php
pag-empresa/vagas.php

incluindo o back-end pro painel de vagas e processo seletivo

incluindo o back-end pro painel de vagas e processo seletivo

---

pag-empresa/css/PERFIL.css
pag-empresa/perfil.php

estilizando tela de perfil

---

pag-aluno/css/painel-de-vagas.css
pag-aluno/css/processo-seletivo.css
pag-aluno/painel-de-vagas.php
pag-aluno/processos-seletivos.php
pag-empresa/css/candidato-vaga.css
pag-empresa/css/dash.css
pag-empresa/css/vagas.css
pag-empresa/dash.php
pag-empresa/vagas-candidato.php
pag-empresa/vagas.php

estilizando tela de aluno, arrumando modais e filtro funcionando

estilizando tela de aluno, arrumando modais e filtro funcionando

---

pag-aluno/index.php
pag-aluno/painel-de-vagas.php
pag-aluno/processos-seletivos.php

umando bug de duplicar vaga por conta do requisito no inner join

arrumando bug de duplicar vaga por conta do requisito no inner join

---

one-page/tela-login/login-one-page.php
pag-adm/components/sidebar-adm.php
pag-aluno/components/header.php
pag-aluno/css/notificacao.css
pag-aluno/css/processo-seletivo.css
pag-aluno/index.php
pag-aluno/meu-curriculo.php
pag-aluno/notificacoes.php
pag-aluno/perfil.php
pag-aluno/processos-seletivos.php

estilzando telas

---

pag-aluno/back-end/salvarCandidato/salvar-candidato.php
pag-empresa/beck-end/crudAluno/aluno-aceitar.php
pag-empresa/beck-end/crudAluno/aluno-deletar.php
pag-empresa/css/candidato-vaga.css
pag-empresa/css/vagas.css
pag-empresa/vagas-candidato.php
pag-empresa/vagas.php

crud de candidato funcionando

---

pag-aluno/css/processo-seletivo.css
pag-aluno/processos-seletivos.php

status da candidatura da vaga

---

pag-aluno/css/processo-seletivo.css
pag-aluno/processos-seletivos.php
pag-empresa/componentes/componentE.css
pag-empresa/css/Candidatos.css
pag-empresa/css/cadastrar-vaga.css
pag-empresa/css/candidato-vaga.css
pag-empresa/css/editar-vaga.css
pag-empresa/css/home.css
pag-empresa/css/vagas.css
pag-empresa/vagas-candidato.php
pag-empresa/vagas.php

status e email de empresa de contato aparece

status e email de empresa de contato aparece

---

pag-aluno/processos-seletivos.php
pag-empresa/beck-end/crudAluno/aluno-deletar.php
pag-empresa/vagas-candidato.php

back-end dos status e mensagens de aceito/nao aceito na vaga

back-end dos status e mensagens de aceito/nao aceito na vaga

---

pag-aluno/back-end/salvarCandidato/delete-processo.php
pag-aluno/css/processo-seletivo.css
pag-aluno/processos-seletivos.php
pag-empresa/vagas-candidato.php

back-end desistir da vaga e coutn de notis de candidatos da vaga

back-end desistir da vaga e coutn de notis de candidatos da vaga

---

pag-aluno/painel-de-vagas.php

arrumando requisitos das vagas apresentando todas

arrumando requisitos das vagas apresentando todas

---

pag-aluno/css/notificacao.css
pag-aluno/css/painel-de-vagas.css
pag-aluno/css/processo-seletivo.css
pag-aluno/notificacoes.php
pag-aluno/painel-de-vagas.php
pag-aluno/processos-seletivos.php
pag-empresa/css/candidato-vaga.css
pag-empresa/vagas-candidato.php

mexendo em detalhes

---

pag-aluno/painel-de-vagas.php
pag-aluno/processos-seletivos.php

back filtro finalizado

---

pag-empresa/beck-end/cadastroVaga/salvarCadastroVaga.php
pag-empresa/cadastrar-vaga.php

arrumando detalhe back vaga

---

pag-adm/aluno.php
pag-adm/back-end/alterar/update.php
pag-adm/back-end/buscas/buscaAluno.php
pag-adm/back-end/buscas/buscaEmpresa1.php
pag-adm/configuracao.php
pag-adm/css/aluno.css
pag-adm/css/configuracao.css
pag-adm/css/empresa.css
pag-adm/css/index.css
pag-adm/empresa.php
pag-adm/etec.php
pag-adm/index.php
pag-adm/js/modal-editar.js
pag-adm/js/pdf.js
pag-adm/perfil.php
pag-empresa/beck-end/buscaAluno/buscaAluno.php
pag-empresa/beck-end/buscaVaga/buscaVaga.php
pag-empresa/beck-end/crudVaga/vaga-delete.php
pag-empresa/candidatos.php
pag-empresa/componentes/sidebar.php
pag-empresa/css/Candidatos.css
pag-empresa/css/vagas.css
pag-empresa/perfil.php
pag-empresa/vagas-candidato.php
pag-empresa/vagas.php

Colocando buscas na empresa

---

pag-adm/adm.php
pag-adm/aluno.php
pag-adm/css/adm.css
pag-adm/css/aluno.css
pag-adm/css/curso.css
pag-adm/css/empresa.css
pag-adm/curso.php
pag-aluno/back-end/update/update.php
pag-aluno/css/perfil.css
pag-aluno/perfil.php

fazendo o update da imagem do aluno

fazendo o update da imagem do aluno

---

pag-aluno/components/header.php
pag-aluno/components/navbar.php
pag-aluno/css/painel-de-vagas.css
pag-aluno/painel-de-vagas.php
pag-empresa/beck-end/buscaAluno/buscaAluno.php
pag-empresa/css/candidato-vaga.css
pag-empresa/vagas-candidato.php
pag-empresa/vagas.php

mais detalhes

---

pag-empresa/beck-end/buscaAluno/buscaAluno.php
pag-empresa/beck-end/buscaAluno/buscaAluno1.php
pag-empresa/candidatos.php
pag-empresa/css/Candidatos.css
pag-professor/perfil.php

Fazendo a empresa ver o curriculo dos candidatos

Fazendo a empresa ver o curriculo dos candidatos

---

pag-adm/msg-empresa.php
pag-empresa/beck-end/buscaAluno/buscaAluno.php
pag-empresa/candidatos.php
pag-empresa/css/Candidatos.css
pag-empresa/css/candidato-vaga.css
pag-empresa/vagas-candidato.php

Terminnado o curriculo

---

pag-empresa/beck-end/buscaAluno/buscaAluno.php
pag-empresa/candidatos.php
pag-empresa/css/Candidatos.css
pag-empresa/css/candidato-vaga.css
pag-empresa/vagas-candidato.php

curriculo feito, faltando apenas o where

curriculo feito, faltando apenas o where

---

pag-aluno/back-end/cadastro/salvarCurriculo.php
pag-aluno/back-end/crudCurriculo/curriculo-delete.php
pag-aluno/curriculo.php
pag-aluno/js/modal-deletar.js
pag-aluno/meu-curriculo.php
pag-empresa/beck-end/buscaAluno/buscaAluno.php
pag-empresa/candidatos.php
pag-empresa/dash.php
pag-empresa/vagas-candidato.php
pag-empresa/vagas.php

alterando back curriculo

---

dao/bdtrampotec.sql
pag-aluno/formulario3.php
pag-aluno/painel-de-vagas.php
pag-empresa/css/PERFIL.css
pag-empresa/css/candidato-vaga.css
pag-empresa/css/config.css
pag-empresa/css/dash.css
pag-empresa/css/edita.css
pag-empresa/css/priv.css
pag-empresa/perfil.php
pag-empresa/vagas-candidato.php

eestilzando tela de perfil empresa e back dos candidatos

eestilzando tela de perfil empresa e back dos candidatos

---

pag-empresa/beck-end/buscaAluno/buscaAluno.php
pag-empresa/beck-end/buscaVaga/buscaVaga.php
pag-empresa/candidatos.php
pag-empresa/css/Candidatos.css
pag-empresa/css/vagas.css
pag-empresa/dash.php
pag-empresa/vagas.php

estilizando telas de empresa

---

pag-aluno/index.php

mudando botao do aluno

---

pag-adm/cadastro-adm.php
pag-adm/cadastro-curso.php
pag-adm/etec.php
pag-aluno/perfil.php

Arrumando modais do adm

---

pag-aluno/perfil.php

excluindo tel do aluno

---

one-page/tela-login/login-one-page.php
one-page/tela-login/login-one-pagee.css
pag-aluno/components/header.php
pag-aluno/contato.php
pag-aluno/css/fale.css
pag-aluno/css/login.css
pag-aluno/login.php
pag-empresa/componentes/sidebar.php
pag-empresa/css/dash.css
pag-empresa/css/login.css
pag-empresa/dash.php
pag-empresa/vagas-candidato.php

finalizando telas de login
